# Generated by Django 5.0.1 on 2024-01-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_mypost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='title',
            field=models.CharField(max_length=35),
        ),
    ]
